name = "Ravencove"
author = "Arteamissing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "886969e7a9081fc3945cf2f63b993f69012584f3ab43112d5f57b2e6417bcbff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
