name = "Ravencove"
author = "Arteamissing"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4726ddc63627ff0492a9164ff6a7426a762dcfd8cdbff04a360ce3a5fc3b63aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
